library(shiny, warn.conflicts = FALSE)
library(shinyjs, warn.conflicts = FALSE)
library(magrittr, warn.conflicts = FALSE)
library(purrr, warn.conflicts = FALSE)
library(RJSONIO)
library(stringr)
library(writexl)
library(zip, warn.conflicts = FALSE)
library(shinyBS)
library(rmarkdown)

source('functions/eFormsParseJSON_basic.r')
source('functions/eFormsParseJSONtext.r')
source('functions/eFormsOrganizeData_byTable_NRSA.r')
source('functions/eFormsOrganizeData_byTable_NCCA.r')
source('functions/eFormsOrganizeData_byTable_NLA.r')
source('functions/eFormsOrganizeData_byTable_NWCA.r')
source('functions/eFormsOrganizeData_byTable_NLA22.r')
source('functions/parseData.R')

metadata.nrsa <- readRDS("data/metadata.nrsa.rds")
metadata.nla <- readRDS("data/metadata.nla.rds")
metadata.ncca <- readRDS("data/metadata.ncca.rds")
metadata.nwca <- readRDS("data/metadata.nwca.rds")