name: Copy R Shiny app to cloud-gov branch and request push to dev

on:
  workflow_dispatch:
    inputs:
      build_deps:
        description: 'Also build R dependencies?'
        required: true
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  copy_code_to_cloud-gov:
    runs-on: ubuntu-latest
    name: Copy default branch code to shiny-app folder within cloud-gov branch

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: cloud-gov

    - name: Delete shiny-app and main-branch folders if they exist
      run: |
        if [ -d "shiny-app" ]; then rm -fr shiny-app; fi
        if [ -d "main-branch" ]; then rm -fr main-branch; fi

    - name: Checkout default branch to main-branch path
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: main-branch

    - name: Copy everything but .git*, Commit, and Push
      if: ${{ success() }}
      run: |
        mkdir shiny-app
        find main-branch/* -maxdepth 0 ! -name ".git*" -print0 | xargs -0 cp -r -t shiny-app
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add shiny-app
        git diff-index --quiet HEAD || git commit -m "Automated workflow from GitHub Actions to copy R Shiny app from default branch"
        git push
      env:
        BUILD_DEPS: ${{ inputs.build_deps }}

  download_and_vendor_dependencies:
    needs: copy_code_to_cloud-gov
    runs-on: ubuntu-latest
    name: Compile and vendor R dependencies for cloud.gov
    defaults:
      run:
        working-directory: /workspace
    container:
      image: cloudfoundry/cflinuxfs4
      volumes: 
       - ${{ github.workspace }}:/workspace

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: cloud-gov

    - name: Setup Git and remove problematic packages
      run: |
        git config --global --add safe.directory $(realpath .)
        git config user.name github-actions
        git config user.email github-actions@github.com
        sudo apt --purge autoremove -y libmariadb-dev libmariadb-dev-compat
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Setup pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          stringr
          devtools
          rlist
          sf
          rjson
          dplyr

    - name: List R dependencies
      run: |
        sed -n -e 's/^.*- name: //p' r.yml | tr -d '\015' | sed -n -e 'H;${x;s/\n/,/g;s/^,//;p;}' | xargs echo packs= >> $GITHUB_ENV

    - name: Download R packages
      run: |
        if [ -d "vendor_r" ]; then rm -fr vendor_r; fi
        Rscript scripts/download_packages.R vendor_r/src/contrib ${{ env.packs }}
      env: 
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy pandoc executables
      run: |
        if [ -d "r-bin" ]; then rm -fr r-bin; fi
        mkdir r-bin
        cp /usr/bin/pandoc r-bin
        git add r-bin
      
    - name: Upload folder debug-outputs to an artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug-outputs
        path: debug-outputs

    - name: Commit & Push
      if: ${{ success() }}
      run: |
        git add vendor_r
        git diff-index --quiet HEAD || git commit -m "Automated workflow from GitHub Actions to vendor R dependencies"
        git push

  request_copy:
    # Note: this step will fail if OWSHINY_ACTION secret is not set up in the repo and should be removed
    name: Request copy uploaded to deployment repo if permitted
    needs: download_and_vendor_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow to copy for deployment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.OWSHINY_ACTION }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'USEPA',
              repo: 'OWShiny',
              workflow_id: 'copy_repo.yml',
              ref: 'develop',
              inputs: {
                "repo_to_copy": context.repo.owner + "/" + context.repo.repo
              }
            })
